### ISSUE TITLE
The same the consumer tag in prod env.

### ISSUE THREAD

**Issue by xj-zh-dev** [wagslane/go-rabbitmq#11]
![image](https://user-images.githubusercontent.com/76473456/118606222-bd87f900-b7e9-11eb-976c-664801cfebc0.png)

**Comment by wagslane** [comment]
Need more info on this. The expected behavior is that if an empty string is used (the default) a name will be generated as per the underlying docs: https://pkg.go.dev/github.com/streadway/amqp?utm_source=godoc#Channel.Consume
