### ISSUE TITLE
How to close logs

### ISSUE THREAD

**Issue by waltkong** [wagslane/go-rabbitmq#122]
![image](https://user-images.githubusercontent.com/25858040/233909318-b6430d20-c5a0-4c4f-8d4c-9b18b913ff1f.png

What should I do to close all Info logs ?

**Comment by sjm1327605995** [comment]
我也想知道，你可以添加一个关闭日志选项吗

**Comment by sjm1327605995** [comment]
I would also like to know, can you add a turn off logging option

**Comment by wagslane** [comment]
Yup. you can provide your own logger that works however you like. WithConsumerOptionsLogger accepts an interface
