### ISSUE TITLE
Remove Tracef logger requirement

### ISSUE THREAD

**Issue by JarlMartinez** [wagslane/go-rabbitmq#123]
The current Logger interface in the package requires the `Tracef` method, however it is not used at all in code.
I'm providing a custom [zap logger](https://github.com/uber-go/zap) to the consumer/publisher/connection options, and zap's doesn't implement such method either. I'd be ok adding the `Tracef` method locally just to satisfy the requirement, but it feels redundant. Is there any real reason to have such method requirement?

**Comment by wagslane** [comment]
Feel free to open a PR to have it removed!

**Comment by abbasegbeyemi** [comment]
Faced the same issue with zap. Just created a PR #138
