### ISSUE TITLE
shall I keep the publisher object alive in a long run program？

### ISSUE THREAD

**Issue by pwli0755** [wagslane/go-rabbitmq#14]
Hi,  Wagner!

What's the best way to use `NewPublisher`?

Shall I init a  `Publisher` as a global object or just create new ones every time I need publish some message？

Considering when publishing messages, the connection may be reset and rebuild in the `chManager`, it seems we need to re-register the `NotifyReturn` and `NotifyFlow` once the connection rebuilt.

**Comment by wagslane** [comment]
Hey there! If I were you I'd try to use the same publisher where possible. That said, I'm not a fan of globals so maybe pads it where it's needed?

**Comment by pwli0755** [comment]
Sorry I didn't make my question clear.

I'm worry about the `NotifyReturn` and the `NotifyFlow` chan will be closed if there are any reconnection in the meantime, if a reconnect happens, maybe we should  re-register these two chans to get more events just like consumer do(re-Consume once reconneted)?

**Comment by wagslane** [comment]
@pwli0755 You don't need to reregister, the publisher will autoreconnect and use the same channels
