### ISSUE TITLE
Declare queue without consuming messages

### ISSUE THREAD

**Issue by danikk741** [wagslane/go-rabbitmq#142]
Hello. Thank you for your work. I tried to declare a queue with "x-dead-letter-exchange" argument to my main exchange. The problem is that I need to pass Handler for consumer but I do not want messages to be consumed. Messages must be handled automatically by TTL and "x-dead-letter-exchange" option.

Basically, I just need to declare exchanges, queue and bindings without handling messages from queue. What do you think about making Handler argument optional or making Declare functions public?

**Comment by xmapst** [comment]
[go-rabbitmq](https://github.com/xmapst/go-rabbitmq)

**Comment by wagslane** [comment]
You might want to just use the base AMQP library for this. Alternatively you can just pass a NO-OP handler

**Comment by ntauth** [comment]
> You might want to just use the base AMQP library for this. Alternatively you can just pass a NO-OP handler

I'm not sure that's really a solution tbf. What if I want to just publish stuff to a lazy DLX queue indefinitely without necessarily consuming anything? This is currently not possible with a "no-op" consumer, or at least, it is, but the handler needs to keep NackRequeuing the messages...
