### ISSUE TITLE
Allow consumers to disable requeuing of messages

### ISSUE THREAD

**Issue by robinvdvleuten** [wagslane/go-rabbitmq#16]
Currently, the delivery is either acknowledge or not based on the bool return value of a consumer. But it is also automatically requeued. 
In some cases I do not want the delivery to be requeued if its body contains for example invalid JSON and it needs to be send to for example a dead letter queue for further introspection. 

I can imagine that a quick solution would be to change the return value of the consumer to something like `func(d Delivery) (bool, bool)` where the second bool indicates if it should be requeued or not. I can easily create a PR for that behaviour but wanted to check it first.

**Comment by wagslane** [comment]
We do need this functionality... That said I worry about the proposed solution because it implies you can Ack AND requeue (which you can't).

Maybe the return value should be an enum? We could do a custom type with three values, rabbitmq.Ack, rabbitmq.NackDiscard, and rabbitmq.NackRequeue?

**Comment by robinvdvleuten** [comment]
An enum would be a way better option indeed! Do you have a preference on how to implement enums in Go?

**Comment by wagslane** [comment]
I even wrote a whole article about it :) https://qvault.io/golang/golang-enum/

**Comment by robinvdvleuten** [comment]
o nice, thanks! I'll come up with something then as a PR

**Comment by wagslane** [comment]
Fixed in #37
