### ISSUE TITLE
Asynchronous reconnection

### ISSUE THREAD

**Issue by timandy** [wagslane/go-rabbitmq#160]
In #145, asynchronous reconnection was changed to synchronous, and we hope to continue supporting asynchronous recovery reconnection. Or can we split the Run() method into two?

**Comment by wagslane** [comment]
Are you running into performance issue? Can you elaborate on the use case

**Comment by timandy** [comment]
Hi @wagslane  In the startup phase of the application, start the mq consumption coroutine.
If the `startGoroutines` fails, the app exit with 1 as design.
If the start is done with none error, then start the asynchronous reconnection.
This is possible in v0.12.3. But then v0.13.0 made breaking changes, which forced us to stay in the old version.

**Comment by wagslane** [comment]
Sorry I don't think we will be going back to that functionality, but you're free to fork!
