### ISSUE TITLE
Can consumer support temporary queues?

### ISSUE THREAD

**Issue by guodongq** [wagslane/go-rabbitmq#167]
In a consumer startup, we want to create a temporary queue bound to an exchange of the fanout type.

The consumer is deployed with multiple pods, and each pod needs to consume all messages sent to the exchange.

Temporary queue and `exclusive` will be used in golang code, more details please refer https://www.rabbitmq.com/tutorials/tutorial-three-go#temporary-queues

**Comment by wagslane** [comment]
Sorry I'm not sure what's being asked here, this sounds more like a comment about what you're doing
