### ISSUE TITLE
Support for VHost

### ISSUE THREAD

**Issue by brianmori** [wagslane/go-rabbitmq#17]
Hi,

would it be possible to support RabbitMQ Virtual Hosts ?

https://github.com/wagslane/go-rabbitmq/blob/7e07dbfd2a1660f07f129d67b0cf29b8acf7e7f2/channel.go#L37

It is necessary to change the Dial to 

- https://pkg.go.dev/github.com/streadway/amqp#DialConfig
- https://pkg.go.dev/github.com/streadway/amqp#Config

I can propose a PR

**Comment by wagslane** [comment]
Makes sense to me!
