### ISSUE TITLE
producer connect pool

### ISSUE THREAD

**Issue by Mikaelemmmm** [wagslane/go-rabbitmq#179]
I now have an API with very high qps, and I have to send mq every time I call the interface. I now use the same producer through jqeger to observe that the throughput does not seem to go up, and the sending is very slow. I wonder if I can join the connection pool to solve it? It is still under investigation.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Mikaelemmmm** [comment]
I adjusted the producer's ChannelMax=100 and found that the number of concurrencies has greatly improved. The default is 2047.

**Comment by wagslane** [comment]
Sounds like this isn't an issue with this library if I'm understanding the issue
