### ISSUE TITLE
Custom Logger broken on shutdown

### ISSUE THREAD

**Issue by brounnoupegreula-7757** [wagslane/go-rabbitmq#182]
hi i try the example logger, and user uber zap as my custom logger

package logger

import (
	"go.uber.org/zap"
)

```
type RabbitMqZapLogger struct {
	Logger *zap.Logger
}

func (l RabbitMqZapLogger) Fatalf(format string, v ...interface{}) {
	l.Logger.Sugar().Fatalf(format, v...)
}

func (l RabbitMqZapLogger) Errorf(format string, v ...interface{}) {
	l.Logger.Sugar().Errorf(format, v...)
}

func (l RabbitMqZapLogger) Warnf(format string, v ...interface{}) {
	l.Logger.Sugar().Warnf(format, v...)
}

func (l RabbitMqZapLogger) Infof(format string, v ...interface{}) {
	l.Logger.Sugar().Infof(format, v...)
}

func (l RabbitMqZapLogger) Debugf(format string, v ...interface{}) {
	l.Logger.Sugar().Debugf(format, v...)
}
```

but after the app shutdown or interupt by user, look like the connection manager (close function) lost zap formating, any idea why like this?

![image](https://github.com/user-attachments/assets/ffbd4c0b-eb6e-43ed-86e7-cc6c708ac3fb)

**Comment by thibleroy** [comment]
Hello,
Use WithConnectionOptionsLogger connection option ?

**Comment by brounnoupegreula-7757** [comment]
i fix this @thibleroy 

WithConnectionOptionsLogger worked :) 

thank you
