### ISSUE TITLE
Credentials are being logged on connection error

### ISSUE THREAD

**Issue by latuszek** [wagslane/go-rabbitmq#190]
Hi,
I've just come into a problem with logged credentials in the connection URL:

> time=2024-10-01T09:30:06.453Z level=INFO source=:0 msg="gorabbit WARN: failed to connect to amqp server amqp://some-user:some-password@127.0.0.1:5671/: dial tcp 127.0.0.1:5671: connect: connection refused"

The credentials should never be written as a plain text log.

To test this you can simply set the wrong URL and try to connect.

**Comment by xBlaz3kx** [comment]
@latuszek I opened a PR to fix your issue.

**Comment by wagslane** [comment]
Fixed in #195
