### ISSUE TITLE
[v0.12.4] Declaring consumers on the same queue name but different exchanges creates bindings on the same queue

### ISSUE THREAD

**Issue by ntauth** [wagslane/go-rabbitmq#192]
I'll make it short, I am declaring two consumers like this:
```go
	rabbitMQSub, err := gorabbitmq.NewConsumer(
		rabbitMQConnWithAck,
		func(d gorabbitmq.Delivery) gorabbitmq.Action {
			return s.onUpdateChatMetadataTask(ctx, d)
		},
		"tx_outbox_tasks_queue",
		gorabbitmq.WithConsumerOptionsRoutingKey("tx_outbox_task"),
		gorabbitmq.WithConsumerOptionsExchangeName("chats"),
		gorabbitmq.WithConsumerOptionsConcurrency(defaultConcurrency),
		gorabbitmq.WithConsumerOptionsLogger(wrappers.NewRabbitMQLoggerWrapper(log.Tech().Sugar())),
	)
```

```go
	rabbitMQSub, err := gorabbitmq.NewConsumer(
		rabbitMQConnWithAck,
		func(d gorabbitmq.Delivery) gorabbitmq.Action {
			return s.onSendExternalMessageTask(ctx, d)
		},
		"tx_outbox_tasks_queue",
		gorabbitmq.WithConsumerOptionsRoutingKey("tx_outbox_task"),
		gorabbitmq.WithConsumerOptionsExchangeName("messages"),
		gorabbitmq.WithConsumerOptionsConcurrency(defaultConcurrency),
		gorabbitmq.WithConsumerOptionsLogger(wrappers.NewRabbitMQLoggerWrapper(log.Tech().Sugar())),
	)
```

Ad here is what I see on the RabbitMQ management page:
<img width="533" alt="image" src="https://github.com/user-attachments/assets/77db849e-65c1-4555-8a61-c474a445571b">

Only one queue is declared, and the `chats` and `messages` exchanges both push to the same queue. Am I missing something?

**Comment by xmapst** [comment]
> I'll make it short, I am declaring two consumers like this:
> 
> ```go
> 	rabbitMQSub, err := gorabbitmq.NewConsumer(
> 		rabbitMQConnWithAck,
> 		func(d gorabbitmq.Delivery) gorabbitmq.Action {
> 			return s.onUpdateChatMetadataTask(ctx, d)
> 		},
> 		"tx_outbox_tasks_queue",
> 		gorabbitmq.WithConsumerOptionsRoutingKey("tx_outbox_task"),
> 		gorabbitmq.WithConsumerOptionsExchangeName("chats"),
> 		gorabbitmq.WithConsumerOptionsConcurrency(defaultConcurrency),
> 		gorabbitmq.WithConsumerOptionsLogger(wrappers.NewRabbitMQLoggerWrapper(log.Tech().Sugar())),
> 	)
> ```
> 
> ```go
> 	rabbitMQSub, err := gorabbitmq.NewConsumer(
> 		rabbitMQConnWithAck,
> 		func(d gorabbitmq.Delivery) gorabbitmq.Action {
> 			return s.onSendExternalMessageTask(ctx, d)
> 		},
> 		"tx_outbox_tasks_queue",
> 		gorabbitmq.WithConsumerOptionsRoutingKey("tx_outbox_task"),
> 		gorabbitmq.WithConsumerOptionsExchangeName("messages"),
> 		gorabbitmq.WithConsumerOptionsConcurrency(defaultConcurrency),
> 		gorabbitmq.WithConsumerOptionsLogger(wrappers.NewRabbitMQLoggerWrapper(log.Tech().Sugar())),
> 	)
> ```
> 
> Ad here is what I see on the RabbitMQ management page: <img alt="image" width="533" src="https://private-user-images.githubusercontent.com/13150392/389849130-77db849e-65c1-4555-8a61-c474a445571b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjI1MDYsIm5iZiI6MTczMzgyMjIwNiwicGF0aCI6Ii8xMzE1MDM5Mi8zODk4NDkxMzAtNzdkYjg0OWUtNjVjMS00NTU1LThhNjEtYzQ3NGE0NDU1NzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA5MTY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNTA4MjcxZjdmMmU0NDIxNWU2MmQ0ZjA1ZWYxOTI0MTRkOTVhN2YxNzRjN2FlNmZiZjYyNDlhZDk3YmYxYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N5UmvLCDj3ycsAO5D7ID6st3PlPgf_99eKG4qYib9NM">
> 
> Only one queue is declared, and the `chats` and `messages` exchanges both push to the same queue. Am I missing something?

看起来是没问题的, 同一个队列绑定两个交换机, 图中的行为是复合预期的
