### ISSUE TITLE
[v0.14.2] The function NewStaticResolver has a bug, the main branch has been fixed, and no new tag has been added

### ISSUE THREAD

**Issue by nooko** [wagslane/go-rabbitmq#197]
![image](https://github.com/user-attachments/assets/05817790-7058-45a7-8d81-094cecf16376)
![image](https://github.com/user-attachments/assets/4999e2d7-bcc5-47f0-b803-26afda09edd7)

**Comment by wagslane** [comment]
new tag 0.15.0 is up
