### ISSUE TITLE
What happens when Concurrency is 0?

### ISSUE THREAD

**Issue by lucaswxp** [wagslane/go-rabbitmq#41]
From the code:

```
// WithConsumeOptionsConcurrency returns a function that sets the concurrency, which means that
// many goroutines will be spawned to run the provided handler on messages
```
Does that mean the option simply handle gorutines and has no effect on number of underlying consumers - actual rabbitmq consumers?

**Comment by wagslane** [comment]
Correct, it should be a single consumer with multiple goroutines
