### ISSUE TITLE
Implementation for graceful shutdown for consumers

### ISSUE THREAD

**Issue by alter123** [wagslane/go-rabbitmq#48]
There seems to be missing case while handling SIGINT, SIGTERM signals in the implementation, if the consumers are running in goroutine.
One possible implementation can be stop listening to new messages (closing the channel), and provide deadline context to running goroutines.

Would like to know if there can more elegant way for handling these case, also open for contributing.

**Comment by miketonks** [comment]
I'm also interested in the correct way to shutdown the consumers gracefully.

Reading through the docs, I can't find a complete example but looks like we should first call `StopConsuming(consumerName)` and then `Disconnect()`

I updated the consumer example and it appears to work ok.

https://github.com/wagslane/go-rabbitmq/pull/51

**Comment by wagslane** [comment]
example given in #51

**Comment by christian-ehmig** [comment]
Seems like StopConsuming was removed in previous releases. How is the current approach for a graceful shutdown of in-flight consumer goroutines? I don't see a way in the current code base how one could wait for running handlers to finish their work and even more important, to send a final ACK before the consumer is finally closed.

**Comment by NicklasWallgren** [comment]
I'm been wondering the same. We should be able to gracefully shutdown the consumers.

1. Stop consuming new message.
2. Let in-flight consumers finish gracefully, and send ACK/NACK.
3. Close the channels.

**Comment by biswaz** [comment]
Looks like there is no way to achieve graceful shutdown with go-rabbitmq. I'm planning to move to the amqp091-go because of this. 

@wagslane Please clarify if graceful shutdown of in-flight consumer goroutines is possible anymore.

**Comment by biswaz** [comment]
My current workaround (although very flaky) is to sleep for 100ms after my waitgroup is done, so that ACK is sent for all the current workers.
```

func (s *Subscriber) StartProcessing(ctx context.Context, processFunc func(message []byte) error, wg *sync.WaitGroup) error {

	conn, err := rabbitmq.NewConn(
		s.RMQUrl,
		rabbitmq.WithConnectionOptionsLogging,
	)
	if err != nil {
		s.logger.Error("failed to create rabbitmq connection", zap.Error(err))
		return err
	}

	var workerWaitGroup sync.WaitGroup

	consumer, err := rabbitmq.NewConsumer(
		conn,
		func(d rabbitmq.Delivery) rabbitmq.Action {
			workerWaitGroup.Add(1)
			defer workerWaitGroup.Done()
			err := processFunc(d.Body)
			if err != nil {
				s.logger.Error("failed to process message", zap.Error(err))
			}
			return rabbitmq.Ack
		},
		s.Queue,
		rabbitmq.WithConsumerOptionsRoutingKey(s.RoutingKey),
		rabbitmq.WithConsumerOptionsExchangeName(s.ExchangeName),
		rabbitmq.WithConsumerOptionsExchangeKind(amqp091.ExchangeTopic),
		rabbitmq.WithConsumerOptionsQueueDurable,
		rabbitmq.WithConsumerOptionsConcurrency(s.MaxConcurrency),
		rabbitmq.WithConsumerOptionsQOSPrefetch(10),
	)

	go func() {
		select {
		case <-ctx.Done():

			// wait for all workers to finish their current work
			workerWaitGroup.Wait()
			// todo proper graceful shutdown
			// might have to use ampq091-go directly
			time.Sleep(100 * time.Millisecond)
			consumer.Close()

			err := conn.Close()
			if err != nil {
				s.logger.Error("failed to close rabbitmq connection", zap.Error(err))
			}

			wg.Done()
		}
	}()

	return err
}
```
