### ISSUE TITLE
Add log level to Printf method of the Logger interface

### ISSUE THREAD

**Issue by metalrex100** [wagslane/go-rabbitmq#72]
Currently it is not possible to define which log-level message has: info or warning or error.
Need to extend Printf method with `logLevel` variable. I can suggest PR.

It's a breaking change, but don't really see how such feature can be added without breaking change.

**Comment by wagslane** [comment]
You can define your own custom logger, I think that's the thing to do. We send all logs through there, and then the user can choose too suppress them how they wish.

**Comment by metalrex100** [comment]
@wagslane for example I want to show only logs with errors. How do I know in my `Sprintf` implementation if message containing error or just some info?

**Comment by wagslane** [comment]
To not make breaking API changes, we could just add all the prefixes to the
strings we log.

**Comment by metalrex100** [comment]
@wagslane so you suggest to make rewrite logs with prefixes with log level?
Before:
```
chManager.logger.Printf("attempting to reconnect to amqp server from error: %v", err)
chManager.logger.Printf("successfully reconnected to amqp server")
```

After:
```
chManager.logger.Printf("[Error]: attempting to reconnect to amqp server from error: %v", err)
chManager.logger.Printf("[Info]: successfully reconnected to amqp server")
```
?

So in my `Printf` implementation I will have to define message log-level by searching substring?
Possible solution, but guess you also understand that not really good.

**Comment by wagslane** [comment]
Yeah, I don't love it either. I'll think about it some more

**Comment by metalrex100** [comment]
@wagslane I see here 2 possible solutions:

1. Add type `LogLevel` with constants and change Logger's interface method `Sprintf` to accept `LogLevel` type parameter:
```go
type LogLevel string

const (
    Debug   = "debug"
    Info    = "info"
    Warning = "warning"
    Error   = "error"
)

type Logger interface {
    Printf(LogLevel, string, ...interface{})
}
```
The big question here is to have `...interface{}` variadic param, because inside my `Printf` implementation I don't really know what will it contain and how I should handle it.

2. Change Logger interface to have separate methods for each log level:
```go
type Logger interface {
    Debug(string)
    Info(string)
    Warn(string)
    Error(string)
}

type MyLogger struct {}

func (m MyLogger) Debug(s string) {
    // do nothing if Debug logs not needed
}

func (m MyLogger) Info(s string) {
    // implement
}

func (m MyLogger) Warn(s string) {
    // implement
}

func (m MyLogger) Error(s string) {
    // implement
}
```

I prefer 2-nd option. It is more clear and allow to easy suppress any log level.

**Comment by metalrex100** [comment]
@wagslane any updates here?

**Comment by wagslane** [comment]
Implemented in 0.9

**Comment by metalrex100** [comment]
@wagslane so instead of further discussion you decided to close provided PR and just implement how you see it?

**Comment by wagslane** [comment]
@metalrex100 Hey there! I was waiting for a couple weeks for your PR to be updated, but it was just sitting here with failing tests.

Yeah so I went ahead with the log levels, the variadic params should work just fine (same as the printf). You can see an example in the default standard logger if you're unsure how to use it.

**Comment by metalrex100** [comment]
@wagslane we were discussing the logger interface, my message was latest, you didn't answer, but just closed PR and implemented your solution 🫤
