### ISSUE TITLE
Notify is connection closed

### ISSUE THREAD

**Issue by kotyara85** [wagslane/go-rabbitmq#74]
Is there a way to notify my app is rmq connection was closed?
This's super important in different cases like change app status to unhealthy
Thanks

**Comment by wagslane** [comment]
I like this idea if someone wants to implement it.

**Comment by LucaWolf** [comment]
The way I've implemented this in a ~~rip-off~~ spin-off project is via WithConnectionOptionNotification/WithChannelOptionNotification that set private "var notifier chan Event" then push various Events when needed. See notifications.go ->raiseEvent of https://github.com/LucaWolf/grabbit
There are also some callbacks on the same idea.
