### ISSUE TITLE
WithPublisherOptionsReconnectInterval is a ConsumerOption. How to use it?

### ISSUE THREAD

**Issue by willthrom** [wagslane/go-rabbitmq#75]
Try to get this option working as currently the publisher got disconnected but not retrying...

Error publishing message: Exception (504) Reason: \"channel/connection is not open\

`err := publisher.Publish(
		[]byte(data),
		[]string{keyRouter},
		rabbitmq.WithPublishOptionsContentType(publishOptions),
		rabbitmq.WithPublishOptionsMandatory,
		rabbitmq.WithPublishOptionsPersistentDelivery,
		rabbitmq.WithPublishOptionsExchange(exchange),
	)`

`publisher, err := rabbitmq.NewPublisher(
		uriRabbit,
		amqp091.Config{},
		// can pass nothing for no logging
		rabbitmq.WithPublisherOptionsLogging,
	)
`

I see in the code the default if 5 seconds, but it seems to not do it with my current config as I keep getting the same error message no stop.

**Comment by wagslane** [comment]
I'm sorry, can you please retype this? I'm not understanding the problem, at first it looks like you're saying that the publish option is being used on the consumer, then something about reconnects?

**Comment by willthrom** [comment]
Sorry, mixed two issues.

The main one is for the publisher doesn't have a reconnect interval Option because the one defined returns a consumer option.

Just try to set to the publisher and change the internal for the retries....
________________________________
