### ISSUE TITLE
open connection problem, why throw Exception (403)

### ISSUE THREAD

**Issue by busyfree** [wagslane/go-rabbitmq#76]
when i use this repo to connect the rmq server ,but it  throw out  `Exception (403) Reason: "username or password not allowed"`.

directlty use  the `github.com/rabbitmq/amqp091-go` repo ,then it can connect success.

test twice is use the same uri config string.

so cause the exception is some config error ?

**Comment by wagslane** [comment]
That's not a problem with this library, I've tested authentication. sounds like you need to check settings or credentials
