### ISSUE TITLE
Use lowercase "f" for Logger interface functions

### ISSUE THREAD

**Issue by pteich** [wagslane/go-rabbitmq#77]
This is not a real issue but I would suggest to use a lowercase `f` for your `Logger` interface function, e.g. `Errorf(string, ...interface{})` instead of `ErrorF(string, ...interface{})`

This way, it is much easier to use existing logger implementations directly as this is the more or less default in the Go landscape (IMHO). In addition, also the Go `stdlib` functions like `Printf()` use it this way.

**Comment by wagslane** [comment]
fixed in 0.10.0
