### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by SrikanthBhandary** [wagslane/go-rabbitmq#78]
Currently all the messages which are processing will be re-enqueued during the interruption.

**Comment by wagslane** [comment]
Correct! That is by design.

**Comment by eric-chao** [comment]
does this finished?

**Comment by vvayne676** [comment]
Hi Wagslane, when I call consumer.Shutdown(), it will shutdown the consumer at once and throw processing message back to queue? 
If that so, is there a way to shutdown the consumer after it processed all the processing messages?

**Comment by johanneswuerbach** [comment]
FYI: There is a proposed change for exactly this https://github.com/wagslane/go-rabbitmq/pull/150
