### ISSUE TITLE
Truncated messages

### ISSUE THREAD

**Issue by aditya-achmad** [wagslane/go-rabbitmq#85]
Hello,
Sometimes I receive truncated message.
`{"position":{"latitude":0.0,"longitude":0.0,"altitude":0.0},"device":{"id":1,"name":"1111","phone":nu`
It supposed to be like this:
`{"position":{"latitude":0.0,"longitude":0.0,"altitude":0.0},"device":{"id":1,"name":"1111","phone":null}}`

And sometimes I receive message with extra string too.
`{"position":{"latitude":0.0,"longitude":0.0,"altitude":0.0},"device":{"id":1,"name":"1111","phone":null}}1111","phone":null}}`

How to solve this issue?

**Comment by wagslane** [comment]
I don't think this has anything to do with this library. If it does, please provide more info and open a new issue
