### ISSUE TITLE
Goroutine pool 

### ISSUE THREAD

**Issue by codeHauler-1** [wagslane/go-rabbitmq#88]
Will Goroutine pool be added？

**Comment by wagslane** [comment]
Not sure what this means? You're able to use n-number of goroutines already

**Comment by codeHauler-1** [comment]
> Not sure what this means? You're able to use n-number of goroutines already

I mean, the current Goroutine will not restart after panic an error?. Whether the ants library can be imported for concurrent execution.

**Comment by codeHauler-1** [comment]
for i := 0; i < options.Concurrency; i++ {
    go handlerGoroutine(consumer, msgs, options, handler)
}

Concurrency=100;
if one handler panic error.Concurrency=100-1.

**Comment by wagslane** [comment]
Ah I see. Yeah that's out of the scope of this project. Your goroutines shouldn't be panicking! Try to fix that problem is what I'd argue.
