### ISSUE TITLE
How to publish message with Headers?

### ISSUE THREAD

**Issue by xj-zh-dev** [wagslane/go-rabbitmq#9]
How to publish message with Headers?

Like below:
       		amqp.Publishing{
			Headers:     headers,
			ContentType: "text/plain",
			Body:        data,
		},

**Comment by xj-zh-dev** [comment]
And how to publish messages with retries???

**Comment by wagslane** [comment]
Please see the Godoc: `WithPublishOptionsHeaders`

Retries are not a built-in functionality to the client - your application should handle them if you need them.

**Comment by xj-zh-dev** [comment]
> Please see the Godoc: `WithPublishOptionsHeaders`
> 
> Retries are not a built-in functionality to the client - your application should handle them if you need them.

I download latest version, and use WithConsumeOptionsBindingExchangeName does not work well.
