### ISSUE TITLE
publisher resource closure issues

### ISSUE THREAD

**Issue by Mikaelemmmm** [wagslane/go-rabbitmq#92]
Every time I call a business method I "new publisher" to push and then "defer close", the memory keeps going up, I use pprof to check that this is indeed the cause, it is not close in time I'm using pprof to check that this is indeed the cause of the problem. Although I know it is better to initialize "single publisher" and then publish after starting the program, this close does not make sense, it feels like it cannot be released.

![image](https://user-images.githubusercontent.com/74481083/204194566-c245c80c-a3c9-4158-8e4d-6dd4805b7d05.png)

**Comment by wagslane** [comment]
Would you mind trying with the latest version on the main branch and letting me know if you're still having issues. Keep in mind you'll need to close the publisher and the connection

**Comment by wagslane** [comment]
Closing for now, if you can reproduce on the latest version please open a new issue with as much logging/metrics as possible.
