### ISSUE TITLE
Error on newConn

### ISSUE THREAD

**Issue by amitrahav** [wagslane/go-rabbitmq#96]
I'm getting an `undefined` error when trying to run the package like the examples...
Am I missing something or the docs need to change?

The error:
```
<file>:18:26: undefined: rabbitmq.Conn
<file>47:30: undefined: rabbitmq.NewConn
<file>:49:12: undefined: rabbitmq.WithConnectionOptionsLogging (exit status 2)

```

Here is my initial rabbitmq file:
```go
import rabbitmq "github.com/wagslane/go-rabbitmq"

var connection rabbitmq.Conn
connection, err := rabbitmq.NewConn(
 getConnectionString(),
 rabbitmq.WithConnectionOptionsLogging,
)
```

This is relevant part of my project's `go.mod`:
```text
go 1.17

require (
   github.com/wagslane/go-rabbitmq v0.10.0
)
```

Thanx

**Comment by wagslane** [comment]
Yeah please check the godoc, the main branch right now has some breaking changes that will be released soon
