### ISSUE TITLE
Question: What happened with rabbitmq.WithConsumeOptionsQuorum

### ISSUE THREAD

**Issue by TheoAbiel** [wagslane/go-rabbitmq#97]
Hello!
I am using a quorum and I don't know how to use it anymore with the new version 0.11.0. Can you please guide me on how to do it?

**Comment by aaqaishtyaq** [comment]
@wagslane, I was thinking of adding a new consumer option to set a queue as a quorum queue. [Here](https://github.com/wagslane/go-rabbitmq/pull/98) is the implementation, Do let me know your thoughts.

**Comment by TheoAbiel** [comment]
Thank you very much! It works like a charm :grin: !
